name: "Update flake.lock"

on:
  workflow_dispatch:
  schedule:
    - cron: "0 8 * * *"

jobs:
  lockfile:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Install Nix
      uses: DeterminateSystems/nix-installer-action@v1
    - name: Update flake.lock
      uses: DeterminateSystems/update-flake-lock@v19
      with:
        git-author-name: 'caem'
        git-author-email: 'caem@dirae.org'
        git-comitter-name: 'caem'
        git-comitter-email: 'caem@dirae.org'
        pr-title: "Automated: Update flake.lcok"
        pr-labels: |
          dependencies
          automated
